MODEL:
  META_ARCHITECTURE: "NetG"
  WEIGHTS: ""
NET_G:
  IN_CHANNELS: 256
  MASK_TYPE: "icassp"
  VERSION: 'version2'
DATASETS:
  TRAIN: ("change_pairs_no2severe",)
  TEST: ("",)
DATALOADER:
  ASPECT_RATIO_GROUPING: false
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (12000,16000)
  MAX_ITER: 18000
  CHECKPOINT_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "output/netG_lr1e-2-no2svr-v3l1/"
