MODEL:
  META_ARCHITECTURE: "NetG"
  WEIGHTS: "output/netG_lr1e-2-no2svr/model_final.pth"
NET_G:
  IN_CHANNELS: 256
  MASK_TYPE: "icassp"
DATASETS:
  TRAIN: ("change_pairs",)
  TEST: ("",)
DATALOADER:
  ASPECT_RATIO_GROUPING: false
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "output/netG_lr1e-2-no2svr/"
