MODEL:
  META_ARCHITECTURE: "NetG"
NET_G:
  IN_CHANNELS: 256
  MASK_TYPE: "icassp"
DATASETS:
  TRAIN: ("change_pairs_severe",)
  TEST: ("",)
DATALOADER:
  ASPECT_RATIO_GROUPING: false
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (18000, 24000)
  MAX_ITER: 27000
  CHECKPOINT_PERIOD: 3000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
