MODEL:
  META_ARCHITECTURE: "NetG"
NET_G:
  IN_CHANNELS: 256
  MASK_TYPE: "icassp"
DATASETS:
  TRAIN: ("change_pairs_no2severe",)
  TEST: ("",)
DATALOADER:
  ASPECT_RATIO_GROUPING: false
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (3000,4000)
  MAX_ITER: 4500
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
