#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-d3-icassp-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.3 NET_G.MASK_CLIP True

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui10x4-d3-icassp-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.3 NET_G.MASK_CLIP True 
#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-v3l1.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-v3l1loss-ui10x5-icassp-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_TIMES 4 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.3 NET_G.G_STEP 0.05 NET_G.VERSION 'version3'

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-v3l1.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-v3l1oss-ui20x5-icassp-clip  NET_G.INTERVAL 20  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_TIMES 5 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.3 NET_G.G_STEP 0.05 NET_G.VERSION 'version3'

python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-v3l1.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-v3l1loss-ui30x5-icassp-d7  NET_G.INTERVAL 30  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 30 NET_G.UPDATE_TIMES 5 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.7 NET_G.G_STEP 0.05 NET_G.VERSION 'version3'

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-v3.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui20x5-icassp-clip-v3  NET_G.INTERVAL 20  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_TIMES 5 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.3 NET_G.G_STEP 0.05 NET_G.VERSION 'version3'

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-v3.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui20x5-selective-clip-v3  NET_G.INTERVAL 20  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_TIMES 4 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.3 NET_G.G_STEP 0.05 NET_G.VERSION 'version3' NET_G.DROP_MODE 'selective'
#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-s10ki20-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000  NET_G.ONLY_G True  NET_G.MASK_CLIP True  # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-gs005-clip-minmin  NET_G.INTERVAL 10  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_TIMES 4 NET_G.UPDATE_MODE 'minmin' NET_G.DROP 0.3 NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-i30-d3-icassp-gs005-clip2  NET_G.INTERVAL 30  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True

#python tools/plain_train_net_wG.py --resume --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ui10-d3random3  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.MASK_TYPE 'random'

#python tools/plain_train_net_wG.py --resume --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-i10-gauss  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.MASK_TYPE 'gaussian'

#python tools/plain_train_net_wG.py --resume --config-file configs/faster-rcnn-g/Net-G-lr1e-2.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ui10x4-d3-icassp-gs005-clip2  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr-scratch.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-scr-ui20x4-icassp-clip  NET_G.INTERVAL 20  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_TIMES 4 NET_G.UPDATE_MODE 'icassp' NET_G.DROP 0.3 NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-i30-d3-icassp-gs005-clip  NET_G.INTERVAL 30  NET_G.START_ITER 10000  NET_G.ONLY_G True NET_G.MASK_CLIP True

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui30x4-d3-icassp-gs005-clip  NET_G.INTERVAL 30  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 30 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-d1-icassp-gs005-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.1 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-d5-icassp-gs005-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.5 NET_G.MASK_CLIP True NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-d7-icassp-gs005-clip2  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.7 NET_G.MASK_CLIP True NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui10x4-d9-icassp-gs005-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.9 NET_G.MASK_CLIP True NET_G.G_STEP 0.05
#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui10x4-d3-icassp-gs005-clip  NET_G.INTERVAL 10  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 10 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 4 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui20x5-d3-icassp-gs005-clip  NET_G.INTERVAL 20  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05


#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui20x5-d3-icassp-gs005-clip  NET_G.INTERVAL 20  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui40x5-d3-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05


#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui40x5-d3-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.G_STEP 0.05 # NET_G.DROP_MODE 'spatial' NET_G.G_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ch-no2svr-ui40x5-d3ch-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True  NET_G.DROP_MODE 'channel' NET_G.G_MODE 'channel' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ch-svr-ui40x5-d3ch-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE 'channel' NET_G.G_MODE 'channel' NET_G.G_STEP 0.05


#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui40x5-d3sp-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui40x5-d3sp-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True  NET_G.DROP_MODE 'spatial' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-no2svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-no2svr-ui40x5-d3ch-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True  NET_G.DROP_MODE 'channel' NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2-svr.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 4 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-svr-ui40x5-d3ch-icassp-gs005-clip  NET_G.INTERVAL 40  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 40 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 5 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE 'channel'  NET_G.G_STEP 0.05

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 2 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ui50x20-d3sp-icassp-clip2  NET_G.INTERVAL 50  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 50 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 20 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE  'spatial'

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 2 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ui25x10-d3sp-icassp-clip  NET_G.INTERVAL 25  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 25 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 10 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE  'spatial'

#python tools/plain_train_net_wG.py --config-file configs/faster-rcnn-g/Net-G-lr1e-2.yaml --config-det configs/faster-rcnn-g/voc_faster_rcnn_R_50_FPN.yaml --num-gpus 2 OUTPUT_DIR output/voc/fasterrcnn-glr1e_2-ui25x10-d3ch-icassp-clip  NET_G.INTERVAL 25  NET_G.START_ITER 10000 NET_G.UPDATE_START 10000 NET_G.UPDATE_INTERVAL 20 NET_G.UPDATE_MODE 'icassp' NET_G.ONLY_G True NET_G.UPDATE_TIMES 10 NET_G.DROP 0.3 NET_G.MASK_CLIP True NET_G.DROP_MODE  'channel'
